require "./lib/print_helper.rb"
require "./lib/regression_data_set.rb"
require "./lib/error_information.rb"
ROOT_PATH					= "./"
LIB_PATH 					= "#{ROOT_PATH}lib/"
SUPERVISED_MODELS_PATH		= "#{LIB_PATH}supervised/"
UNSUPERVISED_MODELS_PATH	= "#{LIB_PATH}unsupervised/"
PREDICTION_MODELS_PATH		= "#{LIB_PATH}predictions/"
PLOTTING_PATH				= "#{LIB_PATH}plotting/"
TUNING_PATH					= "#{LIB_PATH}tuning/"